//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteOfFineArts.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Desigin
    {
        public int DesiginId { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> Date { get; set; }
        public string Mark { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Exhibition { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompetitionId { get; set; }
        public Nullable<int> RewardId { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Reward Reward { get; set; }
        public virtual User User { get; set; }
    }
}
